/**
 * Console data access.
 *
 * Every figure the v2 UI shows comes through here, and there is no branch in
 * this file that invents one. Mock mode serves committed engine output —
 * regenerated by `python scripts/refresh_web_mocks.py`, which drives the real
 * FastAPI app through TestClient — so `npm run dev` and `npm run dev:live`
 * print identical numbers. That equivalence is the point of the split; a
 * hand-written mock breaks it, which is why the old generate_mocks.js is gone.
 */

import type {
  DemoScenario,
  IngestResponse,
  InterveneResponse,
  Intervention,
  NetworkPayload,
  ScoredNetwork,
} from './types';

const LIVE = import.meta.env.MODE === 'live';
const BASE = 'http://localhost:8000';

/**
 * The slider stops.
 *
 * Mirrors SWEEP_LEVELS in scripts/refresh_web_mocks.py. 0.75 is the trigger's
 * own baseline stress on the mock network, so the slider can open on the exact
 * figure the baseline view showed rather than rounding to 0.7 and quietly
 * disagreeing with the panel beside it.
 */
export const STRESS_LEVELS = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 1] as const;

export interface StressStep {
  own_stress: number;
  scores: ScoredNetwork['scores'];
  ranking: string[];
  summary: ScoredNetwork['summary'];
}

interface Sweep {
  trigger_node: string;
  levels: number[];
  steps: StressStep[];
}

async function post<T>(path: string, body: unknown): Promise<T> {
  const response = await fetch(`${BASE}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!response.ok) {
    // The API returns a structured error body (SCHEMA.md §5.6). Surface its
    // detail rather than a bare status, because "422" on stage tells nobody
    // which field the frontend got wrong.
    let detail = response.statusText;
    try {
      const payload = (await response.json()) as {
        error?: { message?: string };
        detail?: string;
      };
      detail = payload?.error?.message ?? payload?.detail ?? detail;
    } catch {
      /* non-JSON error body; the status text is all there is */
    }
    throw new Error(`${path} failed: ${detail}`);
  }
  return response.json() as Promise<T>;
}

async function get<T>(path: string): Promise<T> {
  const response = await fetch(`${BASE}${path}`);
  if (!response.ok) throw new Error(`${path} failed: ${response.statusText}`);
  return response.json() as Promise<T>;
}

/**
 * The network a scenario request should be scored against.
 *
 * `undefined` means the server's default. Anything else is a network this
 * client ingested and now carries with every request, which is what keeps
 * ingestion stateless — see SCHEMA.md §5.6. The frontend never scores
 * anything itself; it only says which network to score.
 */
export type NetworkOverride = NetworkPayload | undefined;

function overrideBody(network: NetworkOverride) {
  return network
    ? {
        network: {
          meta: network.meta,
          nodes: network.nodes,
          edges: network.edges,
          stress_signals: network.stress_signals ?? [],
        },
      }
    : {};
}

export const api = {
  live: LIVE,

  async network(): Promise<NetworkPayload> {
    if (LIVE) return get<NetworkPayload>('/api/network');
    return (await import('../mocks/network.json')).default as unknown as NetworkPayload;
  },

  /**
   * The baseline scoring, with a score for EVERY node.
   *
   * `/api/at-risk` returns scores for the ranked nodes only — 15 of 412 — and
   * the cascade needs `propagation_depth` for all of them to know which wave a
   * node belongs to. An empty scenario through /api/simulate is the same
   * baseline arithmetic over the whole network, so it is one request instead
   * of two and nothing has to be reconstructed on this side.
   */
  async baseline(network?: NetworkOverride): Promise<ScoredNetwork> {
    if (LIVE || network) {
      return post<ScoredNetwork>('/api/simulate', {
        scenario: { stress_overrides: [], interventions: [] },
        ...overrideBody(network),
      });
    }
    return (await import('../mocks/simulate.json')).default as unknown as ScoredNetwork;
  },

  /**
   * Re-score with the trigger's own stress forced to `level`.
   *
   * Live, this is the engine doing the work — the frontend never recomputes a
   * propagation. Offline, it reads the committed sweep, where every stop was
   * produced by that same engine call ahead of time.
   */
  async atStressLevel(
    triggerNode: string,
    level: number,
    network?: NetworkOverride,
  ): Promise<StressStep> {
    // An ingested network has no committed sweep — it did not exist when the
    // mocks were generated — so it always goes to the engine, mock mode or not.
    if (LIVE || network) {
      const scored = await post<ScoredNetwork>('/api/simulate', {
        scenario: {
          stress_overrides: [{ node_id: triggerNode, own_stress: level }],
          interventions: [],
        },
        ...overrideBody(network),
      });
      return {
        own_stress: level,
        scores: scored.scores,
        ranking: scored.ranking,
        summary: scored.summary,
      };
    }

    const sweep = (await import('../mocks/simulate-sweep.json')).default as unknown as Sweep;
    const step = sweep.steps.find((candidate) => candidate.own_stress === level);
    if (!step) {
      // A level the sweep does not carry is a build-time mismatch between this
      // file and refresh_web_mocks.py, not something to paper over with the
      // nearest neighbour — that would show a figure for a stress the user did
      // not select.
      throw new Error(
        `no committed sweep step for own_stress=${level}; re-run scripts/refresh_web_mocks.py`,
      );
    }
    return step;
  },

  async intervene(
    interventions: Intervention[],
    network?: NetworkOverride,
  ): Promise<InterveneResponse> {
    if (LIVE) {
      return post<InterveneResponse>('/api/intervene', {
        baseline_scenario: { stress_overrides: [], interventions: [] },
        interventions,
        ...overrideBody(network),
      });
    }

    // Offline, against an ingested network. The whole offline ingest path is
    // one canned scenario — api.ingest returns the committed response whatever
    // zip is chosen — so the matching committed intervention is the consistent
    // answer here. It funds that network's own top-ranked supplier at the
    // engine's own cost, which is exactly what the console asks for.
    if (network) {
      return (await import('../mocks/ingest-intervene.json'))
        .default as unknown as InterveneResponse;
    }
    return (await import('../mocks/intervene.json')).default as unknown as InterveneResponse;
  },

  /**
   * Build a network from an uploaded archive.
   *
   * Live, this posts the file to /api/ingest and the engine does everything.
   * Offline it returns the committed response — produced by that same endpoint
   * at mock-refresh time, from the real collection directory zipped the way a
   * user would zip it — so the build page is fully replayable with the backend
   * switched off. The file is still read in mock mode, so an empty or
   * obviously-wrong upload fails the same way in both.
   */
  async ingest(file: File): Promise<IngestResponse> {
    if (LIVE) {
      const body = new FormData();
      body.append('file', file);
      const response = await fetch(`${BASE}/api/ingest`, { method: 'POST', body });
      if (!response.ok) {
        let detail = response.statusText;
        try {
          const payload = (await response.json()) as { detail?: string };
          detail = payload?.detail ?? detail;
        } catch {
          /* non-JSON error body */
        }
        throw new Error(detail);
      }
      return response.json() as Promise<IngestResponse>;
    }

    if (file.size === 0) throw new Error('the uploaded file is empty');
    return (await import('../mocks/ingest.json')).default as unknown as IngestResponse;
  },

  /**
   * DEMO_SCENARIO.md §8: never hardcode the demo IDs in application logic.
   * The trigger node, the funded node and the amount all come from here.
   */
  async demoScenario(): Promise<DemoScenario> {
    return (await import('../mocks/demo-scenario.json')).default as unknown as DemoScenario;
  },
};
