/**
 * Console data access.
 *
 * Every figure the v2 UI shows comes through here, and there is no branch in
 * this file that invents one. Mock mode serves committed engine output —
 * regenerated by `python scripts/refresh_web_mocks.py`, which drives the real
 * FastAPI app through TestClient — so `npm run dev` and `npm run dev:live`
 * print identical numbers. That equivalence is the point of the split; a
 * hand-written mock breaks it, which is why the old generate_mocks.js is gone.
 */

import type {
  DemoScenario,
  InterveneResponse,
  Intervention,
  NetworkPayload,
  ScoredNetwork,
} from './types';

const LIVE = import.meta.env.MODE === 'live';
const BASE = 'http://localhost:8000';

/**
 * The slider stops.
 *
 * Mirrors SWEEP_LEVELS in scripts/refresh_web_mocks.py. 0.75 is the trigger's
 * own baseline stress on the mock network, so the slider can open on the exact
 * figure the baseline view showed rather than rounding to 0.7 and quietly
 * disagreeing with the panel beside it.
 */
export const STRESS_LEVELS = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 1] as const;

export interface StressStep {
  own_stress: number;
  scores: ScoredNetwork['scores'];
  ranking: string[];
  summary: ScoredNetwork['summary'];
}

interface Sweep {
  trigger_node: string;
  levels: number[];
  steps: StressStep[];
}

async function post<T>(path: string, body: unknown): Promise<T> {
  const response = await fetch(`${BASE}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!response.ok) {
    // The API returns a structured error body (SCHEMA.md §5.6). Surface its
    // detail rather than a bare status, because "422" on stage tells nobody
    // which field the frontend got wrong.
    let detail = response.statusText;
    try {
      const payload = (await response.json()) as {
        error?: { message?: string };
        detail?: string;
      };
      detail = payload?.error?.message ?? payload?.detail ?? detail;
    } catch {
      /* non-JSON error body; the status text is all there is */
    }
    throw new Error(`${path} failed: ${detail}`);
  }
  return response.json() as Promise<T>;
}

async function get<T>(path: string): Promise<T> {
  const response = await fetch(`${BASE}${path}`);
  if (!response.ok) throw new Error(`${path} failed: ${response.statusText}`);
  return response.json() as Promise<T>;
}

export const api = {
  live: LIVE,

  async network(): Promise<NetworkPayload> {
    if (LIVE) return get<NetworkPayload>('/api/network');
    return (await import('../mocks/network.json')).default as unknown as NetworkPayload;
  },

  /**
   * The baseline scoring, with a score for EVERY node.
   *
   * `/api/at-risk` returns scores for the ranked nodes only — 15 of 412 — and
   * the cascade needs `propagation_depth` for all of them to know which wave a
   * node belongs to. An empty scenario through /api/simulate is the same
   * baseline arithmetic over the whole network, so it is one request instead
   * of two and nothing has to be reconstructed on this side.
   */
  async baseline(): Promise<ScoredNetwork> {
    if (LIVE) {
      return post<ScoredNetwork>('/api/simulate', {
        scenario: { stress_overrides: [], interventions: [] },
      });
    }
    return (await import('../mocks/simulate.json')).default as unknown as ScoredNetwork;
  },

  /**
   * Re-score with the trigger's own stress forced to `level`.
   *
   * Live, this is the engine doing the work — the frontend never recomputes a
   * propagation. Offline, it reads the committed sweep, where every stop was
   * produced by that same engine call ahead of time.
   */
  async atStressLevel(triggerNode: string, level: number): Promise<StressStep> {
    if (LIVE) {
      const scored = await post<ScoredNetwork>('/api/simulate', {
        scenario: {
          stress_overrides: [{ node_id: triggerNode, own_stress: level }],
          interventions: [],
        },
      });
      return {
        own_stress: level,
        scores: scored.scores,
        ranking: scored.ranking,
        summary: scored.summary,
      };
    }

    const sweep = (await import('../mocks/simulate-sweep.json')).default as unknown as Sweep;
    const step = sweep.steps.find((candidate) => candidate.own_stress === level);
    if (!step) {
      // A level the sweep does not carry is a build-time mismatch between this
      // file and refresh_web_mocks.py, not something to paper over with the
      // nearest neighbour — that would show a figure for a stress the user did
      // not select.
      throw new Error(
        `no committed sweep step for own_stress=${level}; re-run scripts/refresh_web_mocks.py`,
      );
    }
    return step;
  },

  async intervene(interventions: Intervention[]): Promise<InterveneResponse> {
    if (LIVE) {
      return post<InterveneResponse>('/api/intervene', {
        baseline_scenario: { stress_overrides: [], interventions: [] },
        interventions,
      });
    }
    return (await import('../mocks/intervene.json')).default as unknown as InterveneResponse;
  },

  /**
   * DEMO_SCENARIO.md §8: never hardcode the demo IDs in application logic.
   * The trigger node, the funded node and the amount all come from here.
   */
  async demoScenario(): Promise<DemoScenario> {
    return (await import('../mocks/demo-scenario.json')).default as unknown as DemoScenario;
  },
};
